version: "2"

services:
  app:
    image: reduardo7/docker-host-user
    environment:
      # Required:
      - "HOST_USER_NAME=$USER"
      - "HOST_USER_ID=$UID"
      - "HOST_GROUP_NAME=$(id -g -n $USERNAME)"
      - "HOST_GROUP_ID=$(id -g $USERNAME)"
      # Optional:
      - "USER_SHELL=/bin/bash" # Default: /bin/bash
      - "USER_PASSWORD=$USER" # Default: ${HOST_USER_NAME}
      - "PATH_HOME=/home/$USER" # Default: /home/${HOST_USER_NAME}
