version: "2"

services:
  app:
    #image: reduardo7/docker-host-user
    build:
      context: .
    command: "echo 'User: $$USERNAME' ; echo 'UID: $$UID'"
    environment:
      # Required:
      HOST_USER_NAME: "myuser"
      HOST_USER_ID: "7007"
      HOST_GROUP_NAME: "mygroup"
      HOST_GROUP_ID: "8008"
      # Optional:
      USER_SHELL: "/bin/bash" # Default: /bin/bash
      USER_PASSWORD: "myuserpwd" # Default: ${HOST_USER_NAME}
      PATH_HOME: "/home/myuserhome" # Default: /home/${HOST_USER_NAME}
