version: "2"

services:
  app:
    #image: reduardo7/docker-host-user
    build:
      context: .
    command: "echo 'User: $$USERNAME' ; echo 'UID: $$UID'"
    environment:
      # Required:
      HOST_USER_NAME: "u${USERNAME}"
      HOST_USER_ID: "3003"
      HOST_GROUP_NAME: "g${USERNAME}"
      HOST_GROUP_ID: "7007"
      # Optional:
      USER_SHELL: "/bin/bash" # Default: /bin/bash
      USER_PASSWORD: "123456789" # Default: ${HOST_USER_NAME}
      PATH_HOME: "/home/myuserhome" # Default: /home/${HOST_USER_NAME}
